apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: bitcoindcashd
    app: bitcoindcashd
  name: bitcoindcashd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: bitcoindcashd
    spec:
      containers:
        - name: bitcoindcashd
          image: kuberstack/bitcoindcashd
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              name: bitcoindcashd-rpc
          volumeMounts:
            - mountPath: /srv/bitcoindcashd
              name: bitcoindcashd-pvc
            - mountPath: /etc/bitcoindcashd
              name: bitcoindcashd-conf
              readOnly: true
            - mountPath: /etc/bitcoindcashd-ssl
              name: bitcoindcashd-ssl
              readOnly: true
          resources:
            requests:
              cpu: 0.5
              memory: 512Mi
            limits:
              cpu: 4
              memory: 10000Mi
      volumes:
        - name: bitcoindcashd-pvc
          persistentVolumeClaim:
            claimName: bitcoindcashd-pvc
        - name: bitcoindcashd-conf
          secret:
            secretName: bitcoindcashd-conf
        - name: bitcoindcashd-ssl
          secret:
            secretName: bitcoindcashd-ssl
